[package]
name = "rust-example-project"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.6"
log = "0.4.22"
pico-args = "0.5.0"
reqwest = { version = "0.12.9", features = ["blocking"] }
